services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: abia-smart-school-aggregate-dashboard
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/default-001.conf:/etc/apache2/sites-enabled/default-001.conf
    working_dir: /var/www/html
    environment:
      APP_DEBUG: false
      APP_ENV: production
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata: